Fetch minimal number of commits from remote.

diff --git a/gitsync b/gitsync
--- a/gitsync
+++ b/gitsync
@@ -36,44 +36,78 @@ fi
 
 REMOTE=$1
 
-cd "$(git rev-parse --show-toplevel || echo /-nosuchdirectory-)"
-GITDIR=${PWD#$HOME/}
+topdir="$(git rev-parse --show-toplevel)"
+[ -z "$topdir" ] && exit 1
 
-# we need two named pipes: local-to-remote and remote-to-local
+rel_topdir=${PWD#$HOME/}
+local_head=$(git rev-parse HEAD)
+
 loc2rem=/tmp/comm$$-loc2rem
 rem2loc=/tmp/comm$$-rem2loc
-trap "rm -f $loc2rem $rem2loc" EXIT
+trap "rm -f $loc2rem $rem2loc /tmp/bundle$$" EXIT
 
 mkfifo $loc2rem $rem2loc
 
 ssh $REMOTE '
-cd '\'"$GITDIR"\'' && \
-git rev-parse @{u} && \
-read bundle && \
-echo "$bundle" | base64 -d > /tmp/git$$ && \
-git fetch -q /tmp/git$$ && \
-git log --oneline @{u}..FETCH_HEAD >&2 && \
-git reset --hard FETCH_HEAD >&2 && \
-rm /tmp/git$$ && \
-read diff && \
-[ -n "$diff" ] && echo "$diff" | base64 -d | git apply -v
+cd '\'"$rel_topdir"\'' && \
+git rev-parse HEAD && \
+( git rev-list @{u}..HEAD | tr "\n" " " && echo ) && \
+read b64_bundle && \
+( \
+if [ -n "$b64_bundle" ]; then \
+  echo "$b64_bundle" | base64 -d > /tmp/git$$ && \
+  git fetch -q /tmp/git$$ && \
+  rm /tmp/git$$; \
+fi \
+) && \
+read new_head && \
+echo "resetting remote to $(git rev-parse --short $new_head)" >&2 && \
+git reset --hard $new_head && \
+read b64_diff && \
+( \
+if [ -n "$b64_diff" ]; then \
+  echo "$b64_diff" | base64 -d | git apply -v; \
+fi \
+)
 ' >$rem2loc <$loc2rem &
 
 exec <$rem2loc >$loc2rem
 
-read remote_origin
-if [ -z "$remote_origin" ]; then
-   # ssh exited, something went wrong
-   exit 1
+read remote_head
+if [ -z "$remote_head" ]; then
+    # ssh exited, something went wrong
+    exit 1
 fi
-#echo "got remote_origin: $remote_origin" >&2
-common_base=$(git merge-base HEAD $remote_origin)
-if [ -z "$common_base" ]; then
-   exit 1
+#echo "got remote_head: $remote_head" >&2
+read remote_revs
+#echo "got remote_revs: $remote_revs" >&2
+
+if [ "$remote_head" != "$local_head" ]; then
+    for rev in $remote_revs; do
+        if [ "$(git merge-base HEAD $rev 2>/dev/null)" = $rev ]; then
+            remote_base=$rev
+            break
+        fi
+    done
+    if [ -z "$remote_base" ]; then
+        echo "$0: cannot find known commit among $(echo $remote_revs); try git pull" >&2
+        exit 1
+    fi
+else
+    remote_base=$local_head
 fi
 
-git bundle create - $common_base.. 2>/dev/null | base64 -w0
-echo
+if [ "$remote_base" != $local_head ]; then
+    echo "sending $(git rev-parse --short $remote_base)..$(git rev-parse --short HEAD)" >&2
+    git bundle create /tmp/bundle$$ $remote_base..HEAD 2>/dev/null
+    cat /tmp/bundle$$ | base64 -w0
+    echo
+else
+    # "git bundle" refuses to create an empty bundle
+    echo
+fi
+
+git rev-parse HEAD
 # use "git diff HEAD" to also catch staged differences
 git diff --binary HEAD | base64 -w0
 echo
